spring:
  application:
    name: techwizapi

  datasource:
    url: jdbc:mysql://45.77.254.148:3306/movie
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hackathon
    password: hackathon

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
