spring:
  application:
    name: techwizapi

  datasource:
    url: jdbc:mysql://localhost:3306/phimmoidb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567890

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
